
services:
  app:
    container_name: keepits-api-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    environment:
      NODE_ENV: development
      REDIS_HOST_LOCALHOST: redis://redis-keepits-api:6379
    ports:
      - "${PORT}:9000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    restart: always
    networks:
      - keepits-api_network

  redis:
    image: redis:7-alpine
    container_name: redis-keepits-api
    ports:
      - "6379:6379"
    networks:
      - keepits-api_network

  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka-keepits-api
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller

      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - keepits-api_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-keepits-api
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=keepits-local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - keepits-api_network

volumes:
  redis_data:
  kafka_data:

networks:
  keepits-api_network:
    driver: bridge
